### ISSUE TITLE
ubuntu build error

### ISSUE THREAD

**Issue by danwerspb** [phillid/paramano#11]
Hello!
Please, give me advice. I build on Ubuntu 16.04
```bash
✘ user@sev-lucky /tmp/paramano master * make      
cc -lgtk-x11-2.0 -lgobject-2.0 -lglib-2.0  paramano.o bat_tray.o common.o config_file.o defaults.o getcore.o getfreq.o getgov.o tray.o paramano_set_interface.o   -o paramano
paramano.o: In function `main':
paramano.c:(.text+0x46): undefined reference to `gtk_init_check'
paramano.c:(.text+0x6b): undefined reference to `g_log'
paramano.c:(.text+0xcd): undefined reference to `gtk_main'
bat_tray.o: In function `show_tooltip':
bat_tray.c:(.text+0x169): undefined reference to `gtk_tooltip_set_text'
bat_tray.o: In function `update':
bat_tray.c:(.text+0x4cb): undefined reference to `gtk_status_icon_set_from_file'
bat_tray.o: In function `bat_tray_init':
bat_tray.c:(.text+0x557): undefined reference to `gtk_status_icon_new'
bat_tray.c:(.text+0x59a): undefined reference to `gtk_status_icon_set_from_file'
bat_tray.c:(.text+0x5ae): undefined reference to `gtk_status_icon_set_has_tooltip'
bat_tray.c:(.text+0x5c2): undefined reference to `g_type_check_instance_cast'
bat_tray.c:(.text+0x5e5): undefined reference to `g_signal_connect_data'
bat_tray.c:(.text+0x5f9): undefined reference to `g_timeout_add'
bat_tray.o: In function `bat_tray_show':
bat_tray.c:(.text+0x632): undefined reference to `gtk_status_icon_set_visible'
bat_tray.o: In function `bat_tray_hide':
bat_tray.c:(.text+0x64d): undefined reference to `gtk_status_icon_set_visible'
config_file.o: In function `config_init':
config_file.c:(.text+0x12c): undefined reference to `g_log'
config_file.o: In function `config_open':
```

**Comment by phillid** [comment]
You are either missing glib2 and/or gtk2, or you need to modify the `LDFLAGS` variable in `config.mk` to suit your environment. It is likely that Ubuntu names these files differently to my system, and some minor tuning is expected, hence `config.mk` is there.

**Comment by danwerspb** [comment]
I noticed that after reorder arguments i have correct build
Links for same issue - https://askubuntu.com/questions/91505/problem-with-compiling-gtk3-program

`cc paramano.o bat_tray.o common.o config_file.o defaults.o getcore.o getfreq.o getgov.o tray.o paramano_set_interface.o -o paramano -lgtk-x11-2.0 -lgobject-2.0 -lglib-2.0`

What I need to fix in the makefile for the correct order of arguments in the build?

**Comment by danwerspb** [comment]
I added to paramano: section.
$(CC)  -o $@ $^ $(LDFLAGS)
 Build is done.

**Comment by phillid** [comment]
That's very strange, and implies that your system's recipes (which the recipe would have been trying to use) are not correct. Glad you solved it though
